# Generated by Django 3.1.5 on 2021-01-26 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
