# Generated by Django 2.1.15 on 2020-10-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='城市名称', max_length=100)),
                ('code', models.CharField(blank=True, default='', help_text='城市编码', max_length=200)),
            ],
        ),
    ]
