# Generated by Django 3.1.5 on 2021-01-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='area',
            field=models.IntegerField(blank=True, default=-1, help_text='城市所属区域'),
        ),
        migrations.AddField(
            model_name='city',
            name='block',
            field=models.IntegerField(blank=True, default=-1, help_text='中部、东部与西部'),
        ),
        migrations.AddField(
            model_name='city',
            name='ifin40',
            field=models.BooleanField(default=False, help_text='是否属于40城市'),
        ),
        migrations.AddField(
            model_name='city',
            name='ifin90',
            field=models.BooleanField(default=False, help_text='是否属于90城市'),
        ),
        migrations.AddField(
            model_name='city',
            name='line',
            field=models.IntegerField(blank=True, default=-1, help_text='几线城市', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='special_area',
            field=models.IntegerField(blank=True, default=-1, help_text='是否属于长三角，珠三角，环渤海', null=True),
        ),
    ]
