# Generated by Django 3.2 on 2021-06-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20210126_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='info_block',
            field=models.JSONField(help_text='城市区块信息', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='num_block',
            field=models.IntegerField(default=1, help_text='城市区块数'),
        ),
    ]
