# Generated by Django 3.2 on 2021-06-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0003_auto_20210617_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='info_block',
            field=models.JSONField(default={'info': []}, help_text='城市区块信息'),
        ),
    ]
