# Generated by Django 3.2 on 2021-06-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0004_alter_city_info_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='info_block',
            field=models.JSONField(default={'delete_block': [], 'info': []}, help_text='城市区块信息'),
        ),
        migrations.AlterField(
            model_name='city',
            name='num_block',
            field=models.IntegerField(default=0, help_text='城市区块数'),
        ),
    ]
