# Generated by Django 3.1.5 on 2021-01-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('city_or_area', models.BooleanField(default=True)),
                ('area', models.IntegerField(default=-1)),
                ('city', models.IntegerField(null=True)),
                ('price', models.FloatField(default=0)),
                ('price_under_90', models.FloatField(default=0)),
                ('price_above_144', models.FloatField(default=0)),
                ('price_90_144', models.FloatField(default=0)),
                ('index_value', models.FloatField(default=0)),
                ('index_value_under90', models.FloatField(default=0)),
                ('index_value_above144', models.FloatField(default=0)),
                ('index_value_90144', models.FloatField(default=0)),
                ('area_volume', models.FloatField(default=0, help_text='总成交面积')),
                ('area_volume_under_90', models.FloatField(default=0, help_text='总成交面积u90')),
                ('area_volume_above_144', models.FloatField(default=0, help_text='总成交面积a144')),
                ('area_volume_90_144', models.FloatField(default=0, help_text='总成交面积90-144')),
                ('trade_volume', models.IntegerField(default=0)),
                ('volume_year_on_year', models.FloatField(default=0)),
                ('volume_chain', models.FloatField(default=0)),
                ('year_on_year_index', models.FloatField(default=0)),
                ('chain_index', models.FloatField(default=0)),
                ('year_on_year_index_above144', models.FloatField(default=0)),
                ('chain_index_above144', models.FloatField(default=0)),
                ('year_on_year_index_under90', models.FloatField(default=0)),
                ('chain_index_under90', models.FloatField(default=0)),
                ('year_on_year_index_90144', models.FloatField(default=0)),
                ('chain_index_90144', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CalculateResultBase09',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('trade_volume', models.IntegerField(default=0)),
                ('volume_year_on_year', models.FloatField(default=0)),
                ('volume_chain', models.FloatField(default=0)),
                ('city_or_area', models.BooleanField(default=True)),
                ('area', models.IntegerField(default=-1)),
                ('city', models.IntegerField(null=True)),
                ('price_under_90', models.FloatField(default=0)),
                ('price_above_144', models.FloatField(default=0)),
                ('price_90_144', models.FloatField(default=0)),
                ('year_on_year_index', models.FloatField(default=0)),
                ('chain_index', models.FloatField(default=0)),
                ('year_on_year_index_above144', models.FloatField(default=0)),
                ('chain_index_above144', models.FloatField(default=0)),
                ('year_on_year_index_under90', models.FloatField(default=0)),
                ('chain_index_under90', models.FloatField(default=0)),
                ('year_on_year_index_90144', models.FloatField(default=0)),
                ('chain_index_90144', models.FloatField(default=0)),
                ('index_value', models.FloatField(default=0)),
                ('index_value_under90', models.FloatField(default=0)),
                ('index_value_above144', models.FloatField(default=0)),
                ('index_value_90144', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CityIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('trade_volume', models.IntegerField(default=0)),
                ('area_volume', models.FloatField(default=0, help_text='总成交面积')),
                ('area_volume_under_90', models.FloatField(default=0, help_text='总成交面积u90')),
                ('area_volume_above_144', models.FloatField(default=0, help_text='总成交面积a144')),
                ('area_volume_90_144', models.FloatField(default=0, help_text='总成交面积90-144')),
                ('price_under_90', models.FloatField(default=0)),
                ('price_above_144', models.FloatField(default=0)),
                ('price_90_144', models.FloatField(default=0)),
            ],
        ),
    ]
