# Generated by Django 3.1.5 on 2021-02-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateresult',
            name='trade_volume_90_144',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculateresult',
            name='trade_volume_above_144',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculateresult',
            name='trade_volume_under_90',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cityindex',
            name='trade_volume_90_144',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cityindex',
            name='trade_volume_above_144',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cityindex',
            name='trade_volume_under_90',
            field=models.FloatField(default=0),
        ),
    ]
