# Generated by Django 3.2 on 2021-04-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210203_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculateResultBase09',
        ),
        migrations.AddField(
            model_name='calculateresult',
            name='index_value_90144_base09',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculateresult',
            name='index_value_above144_base09',
            field=models.FloatField(default=0, help_text='144平米以上指数值'),
        ),
        migrations.AddField(
            model_name='calculateresult',
            name='index_value_base09',
            field=models.FloatField(default=0, help_text='指数值'),
        ),
        migrations.AddField(
            model_name='calculateresult',
            name='index_value_under90_base09',
            field=models.FloatField(default=0, help_text='90平米以下指数值'),
        ),
        migrations.AlterField(
            model_name='calculateresult',
            name='index_value',
            field=models.FloatField(default=0, help_text='指数值'),
        ),
        migrations.AlterField(
            model_name='calculateresult',
            name='index_value_above144',
            field=models.FloatField(default=0, help_text='144平米以上指数值'),
        ),
        migrations.AlterField(
            model_name='calculateresult',
            name='index_value_under90',
            field=models.FloatField(default=0, help_text='90平米以下指数值'),
        ),
        migrations.AlterField(
            model_name='cityindex',
            name='city',
            field=models.IntegerField(default=0, help_text='城市代码'),
        ),
        migrations.AlterField(
            model_name='cityindex',
            name='price',
            field=models.FloatField(default=0, help_text='总平均价格'),
        ),
        migrations.AlterField(
            model_name='cityindex',
            name='price_under_90',
            field=models.FloatField(default=0, help_text='90平米以下平均价格'),
        ),
        migrations.AlterField(
            model_name='cityindex',
            name='trade_volume',
            field=models.IntegerField(default=0, help_text='总交易额'),
        ),
        migrations.AlterField(
            model_name='cityindex',
            name='trade_volume_under_90',
            field=models.FloatField(default=0, help_text='90平米以下总交易额'),
        ),
    ]
