# Generated by Django 3.2 on 2021-06-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_genreporttaskrecord_reportfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculateresult',
            name='max_area',
            field=models.FloatField(default=0, help_text='本月交易最大面积'),
        ),
        migrations.AddField(
            model_name='calculateresult',
            name='max_price',
            field=models.IntegerField(default=0, help_text='本月交易最高单价'),
        ),
        migrations.AddField(
            model_name='cityindex',
            name='max_area',
            field=models.FloatField(default=0, help_text='本月交易最大面积'),
        ),
        migrations.AddField(
            model_name='cityindex',
            name='max_price',
            field=models.IntegerField(default=0, help_text='本月交易最高单价'),
        ),
    ]
