# Generated by Django 3.2 on 2021-07-05 12:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0006_cityinfocalculatetaskrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityinfoCalculateTaskRecord',
            new_name='CityIndexCalculateTaskRecord',
        ),
    ]
