# Generated by Django 3.1.4 on 2020-12-06 14:44

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('file', models.FileField(upload_to='origin_data')),
                ('code', models.CharField(blank=True, default='', max_length=100)),
                ('city_id', models.IntegerField(default=0)),
                ('start', models.CharField(blank=True, default='', max_length=100)),
                ('end', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', jsonfield.fields.JSONField(default=[])),
                ('content', jsonfield.fields.JSONField(default=[])),
                ('file',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.datafile')),
            ],
        ),
    ]
