# Generated by Django 3.1.4 on 2020-12-10 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculate', '0003_auto_20201207_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=200)),
                ('type', models.CharField(blank=True, default='model', max_length=50)),
                ('kwargs', jsonfield.fields.JSONField(default={})),
                ('start', models.DateTimeField(auto_now_add=True, null=True)),
                ('end', models.DateTimeField(null=True)),
                ('status', models.CharField(blank=True, default='START', max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceSequenceCalculateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_current_id', models.IntegerField(default=0)),
                ('file_last_month_id', models.IntegerField(default=0)),
                ('file_last_year_id', models.IntegerField(default=0)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('details', jsonfield.fields.JSONField(default={})),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='calculate.calculatetask')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCalculateResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=100)),
                ('record_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('details', jsonfield.fields.JSONField(default={})),
                ('data_file',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.datafile')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to='calculate.calculatetask')),
            ],
        ),
    ]
