# Generated by Django 3.2.3 on 2021-06-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0004_calculatetask_modelcalculateresult_pricesequencecalculateresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='city_id',
            new_name='city_code',
        ),
    ]
