# Generated by Django 3.2.3 on 2021-06-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0005_rename_city_id_datafile_city_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='template_file')),
            ],
        ),
    ]
