# Generated by Django 3.2.3 on 2021-06-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0006_templatefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefiles',
            name='city_code',
            field=models.IntegerField(default=0, verbose_name='城市编号'),
        ),
    ]
